### ISSUE TITLE
`dev-client` qr code scheme does not work for underscores in app slug

### ISSUE THREAD

**Issue by homburg** [expo/expo-github-action#251]
### Description of the bug
If you have underscores in your app slug and are using `expo-dev-client` builds, the pr preview QR codes will not work.

### To Reproduce

1. Create expo project with underscore in app slug, eg: https://github.com/homburg/HelloExpo/pull/1
2. Use expo preview action to generate QR code
3. scan QR code to load EAS update in dev-client app build

#### Expected behavior
Expected the installed dev-client app to load the update from the QR code

#### Actual behavior
Received a system error message, (paraphrased): "No apps are registered for this url"

### Additional context
As seen in this example pull-request: https://github.com/homburg/HelloExpo/pull/1:

The app with app slug: `hello_expo` generates an url scheme registration in `AndroidManifest.xml` as `<data android:scheme="exp+helloexpo"/>` (without underscore).

The preview action generates a qr code with the `appScheme` query variable set [verbatim from the `slug` config value.](https://github.com/expo/expo-github-action/blob/b547b4d94a73f2010edbb73d6eab211ce982427d/src/eas.ts#L87)

The mismatch between registered scheme and QR code scheme results in an error.

**Comment by homburg** [comment]
Actually seems like an issue that `appScheme` for the QR code is generated from the `slug` value instead of `scheme` value(s) compared to this: https://github.com/expo/expo-github-action/issues/214#issuecomment-1599383864 unless I'm misunderstanding @byCedric

**Comment by byCedric** [comment]
Hi @homburg! Thanks for creating this issue. There seems to be some confusion around the slug, schemes, and how they relate to the QR codes from `expo/expo-github-action/preview`. 

- `expo-github-action` can create two types of QR codes, for `expo-go`, or `dev-build` (dev clients) -- [we create these URLs here](https://github.com/expo/expo-github-action/blob/main/src/eas.ts#L68-L94)
  - this is resolved and generated in the `getVariables` method of the `expo/expo-github-action/preview` [code here](https://github.com/expo/expo-github-action/blob/main/src/actions/preview.ts#L106-L152)
- The `expo-dev-client` package has a plugin that adds a specific `exp+<slug>`, as scheme, to your project ([see plugin code](https://github.com/expo/expo/blob/main/packages/expo-dev-client/plugin/src/getDefaultScheme.ts#L8-L30)).
  - this plugin actually uses the `slug` config option, and not the `scheme` property.

One thing that seems to be missing or incorrect, is that the plugin removes specific characters from this generated `exp+<slug>` scheme ([here](https://github.com/expo/expo/blob/main/packages/expo-dev-client/plugin/src/getDefaultScheme.ts#L17)). I think this is affecting you right now.

To answer this question:
> Actually seems like an issue that `appScheme` for the QR code is generated from the `slug` value instead of `scheme` value(s) compared to this: https://github.com/expo/expo-github-action/issues/214#issuecomment-1599383864 unless I'm misunderstanding @byCedric
Yep, that's correct, because the `expo-dev-client` plugin uses the `slug` for the generated `exp+helloworld` scheme in your Android manifest. I know it's a bit confusing 🙈

**Comment by byCedric** [comment]
Let me know if this doesn't fix your issue @homburg! 😄

**Comment by homburg** [comment]
Thanks @byCedric that fixes my QR codes!

And thanks for the great explanation. Makes sense that dev-client scheme is independent of `scheme` config (by using the app slug)

**Comment by byCedric** [comment]
Awesome, glad we could resolve it fast. And again, sorry for the confusing property names.
