### ISSUE TITLE
continuous-deploy-fingerprint outputs build ids even if no one was started

### ISSUE THREAD

**Issue by giorgiofellipe** [expo/expo-github-action#290]
### Description of the bug
After running continuous-deploy-fingerprint I have in the outputs the build ids for both platforms, even if they are old ones, no one was started

### To Reproduce
Setup continuous-deploy-fingerprint on a project an run the workflow twice

#### Expected behavior
It is expected (as docs says) to only have the outputs `android-build-id` and `ios-build-id` when they have been started in this run

#### Actual behavior
Always have the outputs `android-build-id` and `ios-build-id`

**Comment by kevinschaffter** [comment]
Can confirm the same issue

**Comment by wschurman** [comment]
This is good feedback. I'll update it to also include boolean outputs indicating whether this run started each build. I think including the build ID that matches in the output is still useful regardless of whether this run started one though, since a subsequent step in the workflow could use that info somehow.
