### ISSUE TITLE
Expo publish - basic action not working

### ISSUE THREAD

**Issue by Derewith** [expo/expo-github-action#38]
### Description of the bug
Hello all! And thanks for the awesome library.
I would like to know if it's something related to Expo, or Github actions itself.
I've set up the basic publish every push to the master repository, but i got an error when the actions is running **expo publish**  
### To Reproduce
```
name: Expo Publish
on:
  push:
    branches: 
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
          node-version: 12.x
    - uses: expo/expo-github-action@v5
      with:
          expo-version: latest
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
    - run: yarn install
    - run: expo publish
```

#### Expected behavior
To publish the package

#### Actual behavior
This is the error 
`##[error]Process completed with exit code 1.`

--- Edit
I've also added EXPO_DEBUG:true
and changed the expo-version to 3.13.1 but the Action is not working..
```
resize:  can't open terminal /dev/tty
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                          │
│   There is a new version of expo-cli available (3.13.8).                                                                                 │
│   You are currently using expo-cli 3.13.1                                                                                                │
│   Install expo-cli globally using the package manager of your choice; for example: `npm install -g expo-cli` to get the latest version   │
│                                                                                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
[15:09:04] Publishing to channel 'default'...
[15:09:05] Building iOS bundle
[15:09:05] connect ECONNREFUSED 127.0.0.1:19003
[15:09:05] Error: connect ECONNREFUSED 127.0.0.1:19003
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)
```

**Comment by byCedric** [comment]
Hi @Derewith! Thanks, happy to make it 😄 I think your issue is related to [#1677](https://github.com/expo/expo-cli/issues/1677). Could you check if you have the `.expo` committed in your repository? If so, try removing that folder from your repository. Also, the issue related to assets (for which the downgrade to `3.13.1` was recommended) is resolved! You can use the latest version again 😄

**Comment by Derewith** [comment]
Hey @byCedric thanks for the hint!
I've removed all the _.expo_ folders in the repository and i'm using the last version in expo-version, but i've got this error..
```
[18:35:58] Unable to find an existing Expo CLI instance for this directory, starting a new one...
[18:35:59] Starting Metro Bundler on port 19001.
[18:35:59] debug Watch mode is not supported in this environment
[18:35:59] debug Checking for a newer version of React Native
[18:35:59] debug Current version: 0.61.4
[18:35:59] debug No release cache found
[18:35:59] debug Checking for newer releases on GitHub
[18:36:00] debug Saving W/"6d6386b01438c6ef0acd213d304b5839" to cache
[18:36:00] debug Latest release: 0.60.0
[18:36:01] Tunnel ready.
[18:36:01] Publishing to channel 'default'...
[18:36:01] An Expo user account is required to proceed.
[18:36:01] Not logged in. Use `function(str) {
  if (arguments.length === 0) return this._name;
  this._name = str;
  return this;
} login -u username -p password` to log in.
##[error]Process completed with exit code 1.
```

**Comment by byCedric** [comment]
Hmm, that's weird, you set your expo credentials properly your config. Is the repo public, if so, can I have a look? If not, do you see "Authenticated as <name>" in the logs of the action?

**Comment by Derewith** [comment]
@byCedric thanks for everything.. now seems to work!

**Comment by byCedric** [comment]
Awesome! Thanks for the follow up, your app looks great 😄 Some extra tips to fine tune your setup:

- It's not recommended to commit `.expo` because it contains information that should only be used on your development machine (not on other systems) _you already did this_ 👍
- It's good to commit `.expo-shared` because that contains information about image optimization, which is good to share. (you can see this in the [template's gitignore too](https://github.com/expo/expo/blob/master/templates/expo-template-blank/gitignore#L2))
- You _may_ (or may not, up to you) commit the lockfile, it's not bad to share this. Although some developers prefer to not do this, it can help speed up the `yarn install` by ±30s and keeping exact versions consistently across multiple machines.

If you encounter anything else, lmk! You can also ping me on the Expo Developers slack if you run into urgent issues. Good luck and have fun developing your app! 😄
